In [116]:
lista = list(range(3,180,4))
lista

[3,
 7,
 11,
 15,
 19,
 23,
 27,
 31,
 35,
 39,
 43,
 47,
 51,
 55,
 59,
 63,
 67,
 71,
 75,
 79,
 83,
 87,
 91,
 95,
 99,
 103,
 107,
 111,
 115,
 119,
 123,
 127,
 131,
 135,
 139,
 143,
 147,
 151,
 155,
 159,
 163,
 167,
 171,
 175,
 179]

In [117]:
import numpy as np
arr = np.array(lista)
arr

array([  3,   7,  11,  15,  19,  23,  27,  31,  35,  39,  43,  47,  51,
        55,  59,  63,  67,  71,  75,  79,  83,  87,  91,  95,  99, 103,
       107, 111, 115, 119, 123, 127, 131, 135, 139, 143, 147, 151, 155,
       159, 163, 167, 171, 175, 179])

In [118]:
mascara = arr%3 == 0
mascara

array([ True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True, False, False,  True, False, False])

In [119]:
n_multiplos = mascara.sum()
n_multiplos

15

In [120]:
arr[mascara] = arr[mascara] * 2
arr

array([  6,   7,  11,  30,  19,  23,  54,  31,  35,  78,  43,  47, 102,
        55,  59, 126,  67,  71, 150,  79,  83, 174,  91,  95, 198, 103,
       107, 222, 115, 119, 246, 127, 131, 270, 139, 143, 294, 151, 155,
       318, 163, 167, 342, 175, 179])

In [121]:
matriz = np.array([arr,arr*2,arr/2])
matriz

array([[  6. ,   7. ,  11. ,  30. ,  19. ,  23. ,  54. ,  31. ,  35. ,
         78. ,  43. ,  47. , 102. ,  55. ,  59. , 126. ,  67. ,  71. ,
        150. ,  79. ,  83. , 174. ,  91. ,  95. , 198. , 103. , 107. ,
        222. , 115. , 119. , 246. , 127. , 131. , 270. , 139. , 143. ,
        294. , 151. , 155. , 318. , 163. , 167. , 342. , 175. , 179. ],
       [ 12. ,  14. ,  22. ,  60. ,  38. ,  46. , 108. ,  62. ,  70. ,
        156. ,  86. ,  94. , 204. , 110. , 118. , 252. , 134. , 142. ,
        300. , 158. , 166. , 348. , 182. , 190. , 396. , 206. , 214. ,
        444. , 230. , 238. , 492. , 254. , 262. , 540. , 278. , 286. ,
        588. , 302. , 310. , 636. , 326. , 334. , 684. , 350. , 358. ],
       [  3. ,   3.5,   5.5,  15. ,   9.5,  11.5,  27. ,  15.5,  17.5,
         39. ,  21.5,  23.5,  51. ,  27.5,  29.5,  63. ,  33.5,  35.5,
         75. ,  39.5,  41.5,  87. ,  45.5,  47.5,  99. ,  51.5,  53.5,
        111. ,  57.5,  59.5, 123. ,  63.5,  65.5, 135. ,  69.5,  71.5,
    

In [45]:
matriz.shape

(3, 45)

In [43]:
print(f'{matriz[0][0]}  {matriz[1][0]}  {matriz[2][0]}')

6.0  12.0  3.0


In [42]:
v0 = np.sqrt((matriz[0]**2).sum())
v0

977.5735266464615

In [48]:
modulo = 0
modulos_fila = 0

def modulo(v):
    v = np.sqrt((v**2).sum())
    return v

modulos_fila = np.apply_along_axis(modulo, 1, matriz)
modulos_fila

array([ 977.57352665, 1955.14705329,  488.78676332])

In [89]:
midict = {"edad": [22, 45, 32], "nombre": ["Juan", "Paula", "Elena"]}

def quita_primer_valor(midict):
  newdict = {}
  for key, value in midict.items():
    newdict[key] = value[1:]
  return newdict

print(quita_primer_valor(midict))  

# def quita_primer_valor(midict):
  
#   return ndict

# res = quita_primer_valor(midict)
# res

{'edad': [45, 32], 'nombre': ['Paula', 'Elena']}


In [100]:
personas = [{"nombre": "Pepe", "edad": 15}, {"nombre": "Juan", "edad": 59}, {"nombre": "Marisa", "edad": 42}, {"nombre": "Eva"}]

def quita_menores(personas, edad_minima = 18):
  newlist = []
  
  for p in personas:
    if (p.get('edad') != None):
      if (p['edad'] >= edad_minima):
        newlist.append(p)
  return newlist

res_18 = quita_menores(personas)
print(res_18)

[{'nombre': 'Juan', 'edad': 59}, {'nombre': 'Marisa', 'edad': 42}]


In [123]:
def reemplaza_maximos (m, repl):
  copia_m = m.copy()
  copia_m = np.apply_along_axis(lambda v: np.put(v, np.argmax(v), repl), 1, copia_m)
  return copia_m

print(reemplaza_maximos(matriz,-10))

[None None None]


In [21]:
import pandas as pd

data1 = {
  'nombre':['Pedro','Pablo','Julio'],
  'cursos':['Fisica','Quimica','Fisica']
}

data2 = {
  'cursos':['Fisica','Quimica'],
  'aula':['101A','102B']
}

df1 = pd.DataFrame(data1)
df1.set_index('nombre',inplace=True)
df2 = pd.DataFrame(data2)
df2.set_index('cursos',inplace=True)

# Crear un diccionario para mapear los cursos a las aulas
curso_aula_dict = dict(zip(df2.index, df2['aula']))

# Agregar una nueva columna 'aula' a df1 utilizando el diccionario
df1['aula'] = df1['cursos'].map(curso_aula_dict)

print(curso_aula_dict)
print(df1)


{'Fisica': '101A', 'Quimica': '102B'}
         cursos  aula
nombre               
Pedro    Fisica  101A
Pablo   Quimica  102B
Julio    Fisica  101A
